### ISSUE TITLE
아이폰 폴라리스 오피스 App 광고차단 요청

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#1]
안녕하세요 아이폰 폴라리스 오피스 App 내에서 

엑셀 문서 편집 시, 동영상 광고 발생 합니다. 광고 제거 부탁드려요

https://apps.apple.com/kr/app/%ED%8F%B4%EB%9D%BC%EB%A6%AC%EC%8A%A4-%EC%98%A4%ED%94%BC%EC%8A%A4-%ED%95%9C%EA%B8%80-pdf-%EC%98%A4%ED%94%BC%EC%8A%A4-%EB%AC%B8%EC%84%9C/id698070860

![IMG_2492](https://user-images.githubusercontent.com/15683789/234893704-6111274f-4ee3-4a5e-a2b8-657c7b6ed76e.png)
![IMG_2493](https://user-images.githubusercontent.com/15683789/234893816-c55ddaf2-4d11-4f5b-a2f3-d35cdbcae58b.png)

**Comment by elsannadisney** [comment]
안녕하세요. 요청글을 읽고, 
main-dns 필터를 수정했습니다. 
main-dns: https://raw.githubusercontent.com/elsannadisney/fzListKor/main/warehouse/maindns.txt

필터를 수정한 후 직접 테스트도 하였습니다. 말씀하신 그 광고가 차단되는 것을 확인할 수 있었습니다.
테스트한 기종은 아이폰 13 프로 맥스이며, 소프트웨어 버전은 iOS 15.7.1, 사용한 앱은 애드가드 프로입니다.

<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test.PNG?raw=true" 
width="200" height="400">
<br/> 위의 사진은 광고를 차단하기 전이며, 아래 사진이 차단한 이후입니다.<br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test2.PNG?raw=true" 
width="200" height="400">
<br/>
마지막으로 테스트한 기종의 애드가드 프로 설정 사진입니다. <br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test3.PNG?raw=true" 
width="200" height="400">
<br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test4.PNG?raw=true" 
width="200" height="400">
<br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test5.PNG?raw=true" 
width="200" height="400">
<br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230428_test6.PNG?raw=true" 
width="200" height="400">
<br/>

**Comment by swbaek81** [comment]
편집 후 돌아가기 누르면 
동영상 광고가 여전히 나와요

![IMG_2497](https://user-images.githubusercontent.com/15683789/235168939-945eabf5-6820-4a42-aa40-09e128be496a.jpeg)

![IMG_2496](https://user-images.githubusercontent.com/15683789/235169037-a03c07e8-b1de-4039-aa9f-278f8c1cbca4.png)

**Comment by elsannadisney** [comment]
애드가드 프로를 정상적으로 설정하셨는지 확인 부탁드려봅니다.
애드가드 프로 접속 -> 사파리 보호가 아닌 DNS 보호를 클릭 -> 
DNS 필터링 클릭 -> DNS 필터 클릭 -> 필터 추가를 클릭 -> https://raw.githubusercontent.com/elsannadisney/fzListKor/main/warehouse/maindns.txt -> 해당 링크 복사 붙여넣기

참고로 덧붙여보자면, 위의 기능을 이용하기 위해서는 
애드가드 프로 우측 하단의 톱니바퀴를 클릭한 후 <br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230429_test.PNG?raw=true" 
width="200" height="400">
<br/>
설정창으로 진입한 다음, 상단의 일반을 클릭합니다. <br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230429_test2.PNG?raw=true" 
width="200" height="400">
<br/>

위의 사진에서 개발자 모드를 확인하신 후 만약 비활성화되어 있다면 활성화시켜주세요.
그래야, DNS 필터를 추가할 수 있는 메뉴가 활성화됩니다.

**Comment by swbaek81** [comment]
dns 필터 추가하고 dns켜져있음에도 

편집 과 돌아가기를 반복하다 보면 동영상광고가 나옵니다

네이버카페 어플 등에서는 광고제거가 됩니다
dns가 켜져있는 상태는 맞는거 같아요

![IMG_2498](https://user-images.githubusercontent.com/15683789/235266437-a59caed9-d51e-4203-aa01-f087da59fe9c.png)

**Comment by elsannadisney** [comment]
폴라리스 오피스 앱을 다시 한번 더 테스트 한 후 
maindns 필터를 업데이트 했습니다.

**Comment by swbaek81** [comment]
ok된거 같습니다
