### ISSUE TITLE
https://m.nate.com/

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#10]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor mobile
fzlistkor dns

아이폰 애드가드 프로

https://m.nate.com/

https://m.news.nate.com/section?mid=s01&sq=630749#list_mainNews

https://m.news.nate.com/section?mid=m01&sq=943666

![IMG_2515](https://user-images.githubusercontent.com/15683789/236599633-e34d5f4e-c3ca-47dc-817b-2c1c4e98c48d.png)
![IMG_2514](https://user-images.githubusercontent.com/15683789/236599636-a935e241-d1f4-4b7d-8a47-72392645ac86.png)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다.
