### ISSUE TITLE
aagag.com/

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#11]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor mobile
fzlistkor dns

아이폰 애드가드 프로

https://aagag.com/

![IMG_2516](https://user-images.githubusercontent.com/15683789/236610433-c591d19b-1a9b-4be9-a1e0-0a9e8caa379b.jpeg)
![IMG_2517](https://user-images.githubusercontent.com/15683789/236610438-8bb8a390-2f46-4a7c-b9f6-903dd8a9f6cc.png)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다.
