### ISSUE TITLE
m.ruliweb.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#12]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor mobile
fzlistkor dns

아이폰 애드가드 프로

https://m.ruliweb.com/community/board/300143/read/61370640

![IMG_2520](https://user-images.githubusercontent.com/15683789/236610921-e89d1b4c-5c0a-4f39-922b-f8081323a178.png)
![IMG_2519](https://user-images.githubusercontent.com/15683789/236610928-6948068b-938e-43c5-a26b-d7089534d084.png)
![IMG_2518](https://user-images.githubusercontent.com/15683789/236610931-3c4eb86d-baa6-4efb-8387-aba9d185a60f.jpeg)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다.
