### ISSUE TITLE
www.ddanzi.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#16]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor mobile
fzlistkor dns

아이폰 애드가드 프로

https://www.ddanzi.com/free/771241372

![IMG_2527](https://user-images.githubusercontent.com/15683789/236611602-fe4846b2-174b-4f92-8b75-ec9080f8309b.jpeg)

**Comment by elsannadisney** [comment]
요청글을 읽고,  mainfiltermobiler 필터를 수정하였습니다.
