### ISSUE TITLE
aagag.com/mirror

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#17]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor mobile
fzlistkor dns

아이폰 애드가드 프로

https://aagag.com/mirror/

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/c2a932d1-07ad-436e-84cd-b9764e2ffa5d)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정하였습니다.
