### ISSUE TITLE
www.ppomppu.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#18]
윗부분이 짤려서 나옵니다. 수정 부탁드려요 감사합니다

필터
fzListKor PC
fzListKor DNS

애드가드 윈도우 프로

크롬 브라우저

https://www.ppomppu.co.kr/zboard/view.php?id=freeboard&no=8317487

적용전
![image](https://github.com/elsannadisney/fzListKor/assets/15683789/83938f03-00b7-4bd8-a677-59a90adcce79)

필터 적용후 (윗부분이 짤렸어요)
![image](https://github.com/elsannadisney/fzListKor/assets/15683789/e8105346-d7b9-4bb7-8034-80f3a0e45589)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 일부 수정했습니다.

**Comment by swbaek81** [comment]
혹시 광고 제거된 공백 줄여 주실 수 있을까요? 감사합니다

https://www.ppomppu.co.kr/zboard/view.php?id=ppomppu&page=1&divpage=78&no=463832

광고제거전
![image](https://github.com/elsannadisney/fzListKor/assets/15683789/7fa98723-327e-4bca-89a4-d13450a9fb61)

광고제거후 (공백 높이 줄일수 있는지 하고요)
![image](https://github.com/elsannadisney/fzListKor/assets/15683789/ec6dc2c4-9e34-4925-b057-0fc1e6781d5c)
