### ISSUE TITLE
search.daum.net

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#19]
PC daum 에서 검색을 하고 이미지 탭을 누르면 이미지 볼수 없습니다
수정 부탁드려요 감사합니다.

필터
fzListKor PC
fzListKor DNS

애드가드 윈도우 프로

크롬 브라우저

https://search.daum.net/search?nil_suggest=btn&w=img&DA=SBC&q=%EB%8F%84%EB%A6%AC%EB%8F%84%EB%A6%AC

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/c26a7bc6-859d-4b10-bd6e-ef6c08e8eeba)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다.
