### ISSUE TITLE
m.naver.com/

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#2]
광고 공란 제거 부탁드립니다

아이폰 사파리 

사파리필터와 dns필터 모두 fzlistkor 만 on 상태

https://m.naver.com

![IMG_2499](https://user-images.githubusercontent.com/15683789/235297241-c378e5ff-909c-4542-956f-8ff644c413cd.jpeg)

**Comment by elsannadisney** [comment]
mainfilter 필터를 수정하였습니다. 
mainfilter: https://raw.githubusercontent.com/elsannadisney/fzListKor/main/warehouse/mainfilter.txt
