### ISSUE TITLE
filetender.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#20]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor PC
fzlistkor dns

크롬 브라우저

윈도우 애드가드 프로

https://www.filetender.com/cXN8u

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/7e88cad6-be28-4f5d-9e26-7f6a3471ec03)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다.
아래 스크린샷은 필터가 적용된 페이지 모습입니다.<br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20230512_test.PNG?raw=true" 
width="700" height="400">
<br/>
