### ISSUE TITLE
ohmynews.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#22]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor PC
fzlistkor dns

크롬 브라우저

윈도우 애드가드 프로

https://www.ohmynews.com/

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/ea561ad8-75a0-460c-aff8-a37a06694c2b)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/0a7a500d-86e8-4b1d-8fb1-2f7b67778abb)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/4d5ade0b-4920-4638-9b4b-db2b350c98d6)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다.
