### ISSUE TITLE
mlbpark.donga.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#25]
광고제거 부탁드립니다 감사합니다

새로고침 하다보면 파워링크 광고가 나옵니다

사용필터
fzlistkor PC
fzlistkor dns

크롬 브라우저

윈도우 애드가드 프로

https://mlbpark.donga.com/mp/b.php?p=1&b=bullpen&id=202305180081357351&select=&query=&user=&site=&reply=&source=&pos=&sig=h4aRSY-Y6hXRKfX2h3a9Sg-gLmlq

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/d348e508-e617-4d19-9507-bdfc5f3460a0)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정하였습니다.
