### ISSUE TITLE
inven.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#27]
공백제거 부탁드립니다 감사합니다

사용필터
fzlistkor PC
fzlistkor dns

크롬 브라우저

윈도우 애드가드 프로

https://www.inven.co.kr/board/webzine/2097/2076443

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/718ad579-5d9e-4eb8-94f8-45cf6b6fe747)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정하였고, maindns 필터를 개선하였습니다.
