### ISSUE TITLE
yachuk.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#28]
광고제거 부탁드립니다 감사합니다

사용필터
fzlistkor PC
fzlistkor dns

크롬 브라우저

윈도우 애드가드 프로

https://yachuk.com/news/articleView.html?idxno=116110

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/7dae51e8-466a-431f-931e-10ed0b6b417b)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다.
