### ISSUE TITLE
m.inven.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#31]
fzlistkor mobile
아이폰
사파리
adguard 프로

https://m.inven.co.kr/board/webzine/2097/2150348
공백제거 부탁드립니다 감사합니다

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/0447754f-26ee-4eec-979b-2ed2b963f7a2)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/3d51f814-0654-4efc-8b23-938984285938)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다.

**Comment by swbaek81** [comment]
필터업데이트해도 계속 광고가 나옵니다

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/586b8a00-5bda-460a-b029-e3d258002c39)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/c1689ff7-c7ed-4de3-b476-c43169fbb3a3)

**Comment by elsannadisney** [comment]
다시 한번 더 테스트 해보시겠어요?

**Comment by elsannadisney** [comment]
광고가 차단되지 않는 이유를 알았습니다. 저는 마이크로쉴드를 이용 중입니다. 그래서, 광고가 출력되지 않는 것이었어요. 해당 사이트는 애드쉴드가 설치된 것으로 보입니다. 일반적인 규칙으로 광고를 차단할 수가 없는 것 같아보여요. 마이크로쉴드를 이용해주세요. 죄송합니다.

**Comment by elsannadisney** [comment]
마이크로쉴드로 광고를 제거하는데 성공했지만, 여백이 남습니다. 해당 여백은 제거할 수 있으므로 제거토록 하겠습니다.

**Comment by elsannadisney** [comment]
테스트를 추가로 진행해본 결과, 게시판을 제외한 인벤의 다른 부분은 일반적인 규칙으로 광고가 제거되나, 안티 애드블록 시스템이 작동하므로 마이크로쉴드를 필수적으로 사용해야만 되더군요. 여기까지가 최선인 것 같습니다.
