### ISSUE TITLE
goodgag.net

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#37]
fzlistkor mobile
아이폰
사파리
adguard 프로

공백 제거 부탁드려요 감사합니다

https://www.goodgag.net/issue/?page=1

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/82c4e2b5-05a5-4dbd-a57e-b62fe2b9e955)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다.
