### ISSUE TITLE
m.sports.chosun.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#42]
fzlistkor mobile
아이폰
사파리
adguard 프로

광고제거 부탁드려요 감사합니다

https://m.sports.chosun.com/

https://m.sports.chosun.com/entertainment/2023-10-08/202310090100053360007235

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/95f30320-192b-4ca9-aa48-879a307769e5)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/1800eb0d-27b3-45ea-95ea-16340bdadc21)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 일부 수정했습니다.

**Comment by swbaek81** [comment]
상단공백은 남더라고요 제거가 혹시 가능할까요?

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/31f76bf3-52f4-4a09-bf53-53826b43e4f5)

**Comment by elsannadisney** [comment]
웹사이트 코드자체를 수정하지 않는 한 저것 만큼은 어려울 것 같습니다. 타 외부 필터들도 저 여백은 없애지 못했습니다.

**Comment by elsannadisney** [comment]
mainfiltermobile 필터를 수정하였습니다. 이제 상단의 여백이 제거됩니다.

**Comment by swbaek81** [comment]
공백제거 부탁드려요 감사합니다

https://m.sports.chosun.com/entertainment/2023-10-08/202310090100053360007235

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/875e1b6b-d751-4bb3-a023-a43d760259d5)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정하였습니다.
