### ISSUE TITLE
tvhot.cc

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#44]
fzListKor 피시필터
win10
엣지브라우저
adguard 

광고제거 부탁드립니다 감사합니다

https://tvhot.cc/

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/bd8cbf6f-01c8-4b6d-9f85-b88df5399c85)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터와 maindns 필터를 수정하였습니다.
