### ISSUE TITLE
m.sportalkorea.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#45]
아이폰 사파리 애드가드프로
fzlistkor mobile

광고차단 부탁드려요 감사합니다

https://m.sportalkorea.com/news/view.php?gisa_uniq=2023101008184815&section_code=40&newsstand=1

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/4f923fa5-1850-4138-abef-1b107a9583ca)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/5afd2534-c03f-4b9b-a290-7d91b034ce1e)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다.
