### ISSUE TITLE
m.starnewskorea.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#48]
아이폰 사파리 애드가드프로

fzlistkor mobile 

공백제거 부탁드려요 감사합니다

https://m.starnewskorea.com/view.html?no=2023101008165140095&SPTK&ref=

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/67d258f5-6e89-4ea6-9fd7-b3e4e341251e)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다.
