### ISSUE TITLE
m.sports.naver.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#51]
광고차단 부탁드립니다 감사합니다

fzlistkor모바일 마이크로쉴드
아이폰 사파리 애드가드프로

https://m.sports.naver.com/kfootball/index

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/aca401e8-3ff2-42fe-8246-570e66bd043e)

**Comment by elsannadisney** [comment]
요청글을 읽고 fzlistkormobile 필터를 수정했습니다.

**Comment by elsannadisney** [comment]
추가로 mainfilterpc 필터도 수정하였습니다. 감사합니다.
