### ISSUE TITLE
game.naver.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#52]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

https://game.naver.com/esports/League_of_Legends/board

https://game.naver.com/esports/Valorant/board

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/68619e63-4f13-4f16-8fe3-fcc8cb87c0c1)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다.

**Comment by elsannadisney** [comment]
추가로 mainfilterpc 필터도 수정하였습니다. 감사합니다.
