### ISSUE TITLE
sports.news.naver.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#55]
광고차단 부탁드립니다 감사합니다

fzlistkor 데스크탑
윈10 애드가드프로 엣지브라우저

https://sports.news.naver.com/wfootball/index

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/9d148058-34d6-4289-b045-e5a97449fdda)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다. 감사합니다.
