### ISSUE TITLE
hani.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#56]
정상기사인데 차단되고 있는거 같습니다. 감사합니다

fzlistkor데스크탑
윈10 애드가드프로 엣지브라우저

https://www.hani.co.kr/

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/cf838a0e-3fa9-4c7a-a3bf-9bbd9ffed4f4)

**Comment by elsannadisney** [comment]
요청글을 읽고 테스트를 진행해보았습니다만 위의 사진과 같은 문제 현상은 발견할 수 없었습니다. 
위의 사진은 사이트 하단의 멀티미디어 탭 부분에서 문제 현상이 발생한 것으로 보입니다.
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20231125_test.png?raw=true" 
width="600" height="300">

**Comment by swbaek81** [comment]
필터만 켜면 안되네요

윈10 + 엣지브라우저 + 애드가드프로 + 필터전부Off = OK
윈10 + 엣지브라우저 + 애드가드프로 + fzListKor만On  = NG
윈10 + 엣지브라우저 + 애드가드프로 + youslist만On  = NG

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/53c211c8-68fa-4c10-9659-3ea284f807a8)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/3bcbdafa-25ab-4880-a4ec-cb9725957c4a)

**Comment by elsannadisney** [comment]
맥북 프로 2021년형 / Chrome / 애드가드 크롬 확장프로그램을 사용하여 <br/>시도했을 때는 위와 같은 문제가 발생하지 않았습니다. <br/> 혹시, 애드가드 프로그램 업데이트를 시도해보시겠어요?

**Comment by swbaek81** [comment]
윈도우 adguard 최신버전인데 NG 더라고요 

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/bef46a04-c828-4b0e-961f-a63552607085)

**Comment by elsannadisney** [comment]
이유를 알았습니다. <br/>
<img src="https://github.com/elsannadisney/fzListKor/blob/main/Photo/20231125_test4.PNG?raw=true" 
width="600" height="300"><br/>
위의 기능을 비활성화하셔야 합니다. mainfilterpc 필터는 문제가 없었습니다. 
애드가드를 켠 후 > 설정 > 네트워크 >네트워크 설정에서 <br/>
트래픽 필터링 활성화 기능을 사진처럼 비활성화해주시길 바랍니다.

**Comment by swbaek81** [comment]
사진처럼 했더니, 전체 사이트가 광고차단이 전혀 되질 않습니다

**Comment by elsannadisney** [comment]
애드가드 크롬 확장프로그램 버전, 사파리 확장프로그램 버전들을 <br/>
이용할 때는 문제의 현상이 발견되지 않았습니다. <br/>
제가 생각하기에 해당 문제는 애드가드 개발진 측에게 제보해야할 것 같습니다.<br/>

**Comment by swbaek81** [comment]
네 감사합니다

**Comment by swbaek81** [comment]
모든필터를 끄고 ListKR 만 On 시에는 OK 입니다

Only List-KR On -> OK
Only Youslist On -> NG
Only Fzlistkor On -> NG

**Comment by elsannadisney** [comment]
이 문제 현상은 계속해서 주시하도록 하겠습니다. 감사합니다.

**Comment by elsannadisney** [comment]
테스트를 시도한 후 mainfilterpc 필터를 수정하였습니다. 
현재는 애드가드 프로그램을 사용하여 광고차단을 시도해도
위의 문제 현상이 발생하지 않을 것 입니다.
