### ISSUE TITLE
heraldcorp.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#57]
광고제거 부탁드립니다. 감사합니다

fzlistkor데스크탑
윈10 애드가드프로 엣지브라우저

https://heraldcorp.com/view.php?ud=20231030000793

https://heraldcorp.com/view.php?ud=20231026000860

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/47c8f6db-be44-4570-af9f-5ade4745086f)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfilterpc 필터를 수정했습니다. 감사합니다.
