### ISSUE TITLE
mlbpark.donga.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#58]
광고차단 부탁드립니다 감사합니다

fzlistkor모바일 마이크로쉴드
아이폰 사파리 애드가드프로

https://mlbpark.donga.com/mp/b.php?p=1&b=bullpen&id=202311230087658386&select=&query=&subselect=&subquery=&user=&site=&reply=&source=&pos=&sig=h4aTGf2gghTRKfX2h3aXGY-Ahhlq

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/733f9f57-51fb-45de-9942-8595bcbd2e8b)

**Comment by elsannadisney** [comment]
요청글을 읽고, mainfiltermobile 필터를 수정했습니다. 감사합니다.
