### ISSUE TITLE
www.goodgag.net

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#59]
공백제거 부탁드립니다 감사합니다

fzlistkor데스크탑
윈10 애드가드프로 엣지브라우저

https://www.goodgag.net/issue/?page=2

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/a84ffab7-1bda-425d-8487-e022b892d2c7)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfilterpc 필터를 수정했습니다. 감사합니다.

**Comment by swbaek81** [comment]
모바일도 반영부탁드려요 감사합니다

아이폰 사파리 애드가드프로

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
