### ISSUE TITLE
etfcheck.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#60]
광고차단 부탁드립니다 감사합니다

fzlistkor데스크탑
윈10 애드가드프로 엣지브라우저

https://www.etfcheck.co.kr/mobile/main

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/1ed9a630-275d-4390-960e-31c83c036f76)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/6a4d0837-ce7d-4832-b339-ab8f8616ea0c)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfilterpc 필터를 수정했습니다. 감사합니다.

**Comment by swbaek81** [comment]
모바일도 반영부탁드려요 감사합니다

아이폰 사파리 애드가드프로

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
