### ISSUE TITLE
sports.news.nate.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#61]
광고차단 부탁드립니다 감사합니다

fzlistkor데스크탑
윈10 애드가드프로 엣지브라우저

https://sports.news.nate.com/view/20231123n16606

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/94a07fa8-c63e-4a39-aac8-ab8e15ab91f9)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfilterpc 필터를 수정했습니다. 감사합니다.
