### ISSUE TITLE
m.mail.daum.net

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#63]
공백이 사라지기 까지 딜레이 대략1초 걸리는데요 

혹시 빠르게 없어지도록 할순 없을지 문의 드립니다 감사합니다

https://m.mail.daum.net/list/INBOX

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/c144f05f-c831-4260-b05d-7348d08eeac3)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정하였습니다. 감사합니다. <br/> 추가로 <a href="https://m.mail.kakao.com/list/INBOX">https://m.mail.kakao.com/list/INBOX</a> 사이트도 개선 작업을 진행하였습니다.
