### ISSUE TITLE
m.sports.naver.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#64]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

https://m.sports.naver.com/kfootball/index

https://m.sports.naver.com/wfootball/index

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/063a9f98-f9e2-4d1b-a0a1-632cff8aeff1)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
