### ISSUE TITLE
goal.com/kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#65]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

https://www.goal.com/kr

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/f1cb12ff-b6d4-4a06-8d63-97546ed49dee)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. <br/>또한 추가로 mainfilterpc 필터를 수정했습니다. 감사합니다.
