### ISSUE TITLE
m.heraldpop.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#72]
공백제거 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

http://m.heraldpop.com/view.php?ud=202311251943579755216_1

http://m.heraldpop.com/view.php?ud=202311251928279725026_1

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/8ffdafa0-b127-4ba2-a038-f34ad7a0c4da)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
