### ISSUE TITLE
dtoday.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#74]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 에드가드프로
fzlistkor모바일 마이크로쉴드

http://www.dtoday.co.kr/

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/fe90aa88-5b7d-4d04-959d-b6ce2ab8fbbe)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
