### ISSUE TITLE
m.kwnews.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#75]
광고제거 부탁드립니다 감사합니다

아이폰 시파리 에드가드프로
fzlistkor모바일 마이크로쉴드

https://m.kwnews.co.kr/page/view/2023110408072375429

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/6be71302-2126-4a43-9e9f-54478fb668f7)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
