### ISSUE TITLE
m.tf.co.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#77]
광고제거 부탁드립니다 감사합니다

아이폰 사파리 에드가드프로
fzlistkor모바일 마이쿠로쉴드

https://m.tf.co.kr/

https://m.tf.co.kr/read/ptoday/2050726.htm?ref=main_news

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/ca624652-b165-448d-852c-504805b6223c)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/883910a0-2106-4f27-9c2f-7645b596ac47)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다.

**Comment by swbaek81** [comment]
PC도 반영부탁드립니다 감사합니다

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/1ce530f8-5ea7-4f52-8baa-6e57ff0d00ac)


![image](https://github.com/elsannadisney/fzListKor/assets/15683789/ddd22921-979a-4804-8739-1402b8f84160)

**Comment by elsannadisney** [comment]
mainfilterpc 필터도 수정했습니다.
