### ISSUE TITLE
kyeonggi.com 

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#78]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

https://www.kyeonggi.com/article/20231020580088

https://www.kyeonggi.com/article/20231022580159

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/70ee1aec-0844-4a47-a63b-a0f81e0083ce)

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/3d959b4a-bcd5-49ea-b541-e85e1c06808e)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
