### ISSUE TITLE
dprime.kr

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#79]
광고차단 부탁드립니다 감사합니다

아이폰 사파리 애드가드프로
fzlistkor모바일 마이크로쉴드

https://dprime.kr/g2/bbs/board.php?bo_table=dpinfo&wr_id=49227

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/7bcf48b7-fe3c-452b-8f6b-9499699a390f)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfiltermobile 필터를 수정했습니다. 감사합니다.
