### ISSUE TITLE
news.zum.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#80]
공백제거 부탁드립니다 감사합니다

fzlistkor데스크탑 마이크로쉴드
윈10 애드가드프로 엣지브라우저

https://news.zum.com/articles/87206349?cm=news_section_top&r=1&thumb=1

https://news.zum.com/articles/87206593?cm=news_section_top&r=1&thumb=1

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/d3884023-9117-44dd-8d49-7f780fe224e6)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfilterpc 필터를 수정했습니다. 감사합니다.
