### ISSUE TITLE
sports.chosun.com

### ISSUE THREAD

**Issue by swbaek81** [elsannadisney/fzListKor#83]
공백제거 부탁드립니다 감사합니다

fzlistkor데스크탑 마이크로쉴드
윈10 애드가드프로 엣지브라우저

https://sports.chosun.com/entertainment/2023-11-26/202311260100191310026732

https://sports.chosun.com/football/2023-11-26/202311270100191670026750

![image](https://github.com/elsannadisney/fzListKor/assets/15683789/efe23348-9853-4f3b-9da1-8b861f0b2f51)

**Comment by elsannadisney** [comment]
요청글을 읽고 mainfilterpc 필터를 수정했습니다. 감사합니다.
